In [1]:
import numpy as np
import pandas as pd
import json
import csv

from bokeh.plotting import figure
from bokeh.io import output_file, show, save
from bokeh.models import ColumnDataSource
from bokeh.transform import dodge
from bokeh.core.properties import value
from bokeh.models import PanTool, ResetTool, WheelZoomTool, HoverTool, LassoSelectTool, BoxSelectTool

In [2]:
df = pd.read_json("dataset.json", lines=True)

In [3]:
df_p = pd.read_json('dataset_incidents.json', lines=True)

In [4]:
df_suspect = df_p
df_test = df_suspect.groupby([ "participant_relationship",'participant_age']).size().reset_index(name="count")
# df_relationships = df_relationship.drop(df_relationship.index[11])
# df_relationship



# for index, row in df_relationship.iterrows():
#     print(row)

df_relationships = df_test.loc[df_test['participant_relationship'].str.contains("NaN")==False]
# print(df_aquaintance)
df_relationships.set_index('participant_relationship')
df_relationship = df_relationships.loc[df_relationships['participant_relationship'].str.contains('Aquaintance')==False]
df_relationship

# for index, row in df_relationship.iterrows():
#     if "Significant others" or "Neighbor" or "Mass Shooting" or "Family" or "Friends" in row:
#         df_relationship = df_relationship.drop(row)
#     else:
#         continue
# df_relationship

                   participant_relationship  participant_age  count
65                            Armed Robbery              0.0      2
66                            Armed Robbery              1.0      2
67                            Armed Robbery              2.0      2
68                            Armed Robbery              3.0      3
69                            Armed Robbery              4.0      2
70                            Armed Robbery              5.0      3
71                            Armed Robbery              6.0      2
72                            Armed Robbery              8.0      1
73                            Armed Robbery             10.0      2
74                            Armed Robbery             11.0      1
75                            Armed Robbery             12.0      2
76                            Armed Robbery             13.0     10
77                            Armed Robbery             14.0     29
78                            Armed Robbery             15.0     70
79                            Armed Robbery             16.0    129
80                            Armed Robbery             17.0    181
81                            Armed Robbery             18.0    313
82                            Armed Robbery             19.0    283
83                            Armed Robbery             20.0    233
84                            Armed Robbery             21.0    236
85                            Armed Robbery             22.0    193
86                            Armed Robbery             23.0    185
87                            Armed Robbery             24.0    177
88                            Armed Robbery             25.0    157
89                            Armed Robbery             26.0    141
90                            Armed Robbery             27.0    132
91                            Armed Robbery             28.0    122
92                            Armed Robbery             29.0    111
93                            Armed Robbery             30.0    115
94                            Armed Robbery             31.0    108
..                                      ...              ...    ...
822  Significant others - current or former             63.0     15
823  Significant others - current or former             64.0     13
824  Significant others - current or former             65.0     12
825  Significant others - current or former             66.0     10
826  Significant others - current or former             67.0     10
827  Significant others - current or former             68.0     18
828  Significant others - current or former             69.0      9
829  Significant others - current or former             70.0     10
830  Significant others - current or former             71.0     14
831  Significant others - current or former             72.0     13
832  Significant others - current or former             73.0     14
833  Significant others - current or former             74.0      6
834  Significant others - current or former             75.0      6
835  Significant others - current or former             76.0      5
836  Significant others - current or former             77.0      3
837  Significant others - current or former             78.0      5
838  Significant others - current or former             79.0      5
839  Significant others - current or former             80.0      4
840  Significant others - current or former             81.0      4
841  Significant others - current or former             82.0      2
842  Significant others - current or former             83.0      7
843  Significant others - current or former             84.0      3
844  Significant others - current or former             85.0      3
845  Significant others - current or former             86.0      3
846  Significant others - current or former             87.0      2
847  Significant others - current or former             88.0      3
848  Significant others - current or former             92.0      1
849  Significant others - current or former             93.0      2
850  Significant others - current or former             94.0      1
851  Significant others - current or former             96.0      1

[684 rows x 3 columns]

In [ ]:
df_suspect = df_p.loc[(df_p['participant_type'] == "Subject-Suspect")]
df_relationships = df_suspect.groupby([ "participant_relationship"])
# df_relationships = df_relationship.drop(df_relationship.index[11])

df_relationships.describe()

# # df_relation_age = df_relationship.set_index('participant_age')
# df_relations = df_relationship.groupby('participant_relationship')
# df_relations.describe()
# # for index, row in df_relationship.iterrows():

# #     print(row)

# df_aquaintance = df_relationship.loc[df_relationship['participant_relationship'].str.contains("Family")==True]
# # print(df_aquaintance)
# df_aquaintance

In [ ]:
df_suspect = df_p
df_test = df_suspect.groupby([ "participant_relationship",'participant_age']).size().reset_index(name="count")
# df_relationships = df_relationship.drop(df_relationship.index[11])
df_relationship



# for index, row in df_relationship.iterrows():
#     print(row)

df_relationship = df_test.loc[df_test['participant_relationship'].str.contains("NaN")==False]
# print(df_aquaintance)

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
from math import pi
 
# Set data
df = pd.DataFrame({
'group': ['Male','Female','C','D'],
'Armed Robbery': [29.6, 30.9, 30, 4],
'Friends': [27.6, 29.5, 2, 34],
'Family': [34.7, 37.8, 23, 24],
'Gang vs Gang': [23.4, 26.4, 33, 14],
'Significant Others': [38.5, 37.4, 32, 14]
})
 
 
 
# ------- PART 1: Create background
 
# number of variable
categories=list(df)[1:]
N = len(categories)
 
# What will be the angle of each axis in the plot? (we divide the plot / number of variable)
angles = [n / float(N) * 2 * pi for n in range(N)]
angles += angles[:1]
 
# Initialise the spider plot
ax = plt.subplot(111, polar=True)
 
# If you want the first axis to be on top:
ax.set_theta_offset(pi / 2)
ax.set_theta_direction(-1)
 
# Draw one axe per variable + add labels labels yet
plt.xticks(angles[:-1], categories)
 
# Draw ylabels
ax.set_rlabel_position(90)
plt.yticks([10,20,30,40], ["10","20","30",'40'], color="grey", size=10)
plt.ylim(0,40)
 
 
# ------- PART 2: Add plots
 
# Plot each individual = each line of the data
# I don't do a loop, because plotting more than 3 groups makes the chart unreadable
 
# Ind1
values=df.loc[0].drop('group').values.flatten().tolist()
values += values[:1]
ax.plot(angles, values, linewidth=1, linestyle='solid', label="Male")
ax.fill(angles, values, 'b', alpha=0.1)
 
# Ind2
values=df.loc[1].drop('group').values.flatten().tolist()
values += values[:1]
ax.plot(angles, values, linewidth=1, linestyle='solid', label="Female")
ax.fill(angles, values, 'r', alpha=0.1)
 
# Add legend
plt.legend(loc='upper right', bbox_to_anchor=(0.01, 0.01))

In [ ]:
df_gender = df_p.loc[df_p['participant_gender'].str.contains('Female')==True]
df_year = df_gender.loc[df_gender['']]
df_male = df_gender.groupby('participant_relationship')['participant_age']
df_male.describe()

In [ ]:
from bokeh.models import DataRange1d
import bokeh.models
output_file("iris.html")

# Create the figure object
f = figure(plot_width=1000, plot_height=650)

relation = df_relationship[df_relationship["participant_relationship"] == "relation"]


# Now we make a rather small change, namely

# If you get an BAD_COLUMN_NAME error. Reset your kernel. In the next version of Bokeh this will be fixed,
# But at the moment the keys do not update when the data is edited. So running the code multiple times, can
# sometimes result in conflicts.
relation_cds = ColumnDataSource(relation)



# Adding glyphs
f.circle(x=df_relationship["count"], y=df_relationship["participant_age"])

# Save and show the figure


# Dictionary to map name of the species to a color
colormap = {
    'Family' : 'red',
    'Friends' : 'green',
    'Significant other - current or otherwise' : 'blue',
    'Aquaintance' : '#424242',
    'Gang vs Gang' : '#424242',
    'Armed Robbery' : 'orange',
    'Home Invasion': '#424242',
    'Co-worker': '#424242',
    'Drive by - Random victims': '#424242',
    'Home Invasion - Perp Does Not Know Victim': '#424242',
    'Home Invasion - Perp Knows Victim': 'amber',
    'Mass shooting - Random victims': 'brown',
    'Mass shooting - Perp Knows Victims' :'black',
    
    'Neighbor': '#424242',
    'Significant others - current or former': 'teal'
    
}

# Adding a column to the DataFrame (using list comprehension to make the contents of the column)
df_relationship['color'] = [colormap[x] for x in df_relationship['participant_relationship']]

# Now we define the figure again, and this time add the color to the circle plot:

#############################################################################
# Define the output file path
output_file("iris.html")

# Create the figure object
f = figure(plot_width=1000, plot_height=650)

## Adding some style
# You can also use Hex-codes and RGB tuples for the color
f.background_fill_color= '#424242'
# f.background_fill_alpha=0.3

## Add a Title to the plot (We essentially use css properties here)
# You can find all function of f.title, using dir(f.title)
f.title.text="Age and Relationship"
f.title.text_font_size="25px"
f.title.align="center"

## Add some axis information (after all, a plot without axis descriptions is nothing more than abstract art)
f.xaxis.axis_label="Suspect Age"
f.yaxis.axis_label="Reported number of incidents"

# Maybe add some different colors for the labels and the digits as well
# Note how we use f.axis, to apply to both the x and y axis.
f.axis.axis_label_text_color="grey"
f.axis.major_label_text_color="grey"

# Axes geometry
f.x_range=DataRange1d(start=0, end=96)
f.y_range=DataRange1d(start=0, end=350)

hover = HoverTool(tooltips=[("(x,y)", "($x, $y)"), ('relation' , '@relation') ])

# Now we just pick a semi-random selection of tools
f.toolbar.tools = [PanTool(), ResetTool(), WheelZoomTool(), hover, LassoSelectTool(), BoxSelectTool()]

# And let us just move it to the top instead of the side.
f.toolbar_location='above'

#############################################################################
f.circle(x=df_relationship["participant_age"], y=df_relationship["count"], size =df_relationship['count']/3, 
         fill_alpha=0.2, color=df_relationship['color'])
show(f)

In [ ]:
relationships = ['NaN','Aquaintance','Co-worker','Drive by - Random victims', 'Family','Friends', 'Gang vs Gang','Home Invasion - Perp Does Not Know Victim','Home Invasion - Perp Knows Victim','Mass shooting - Random victims','NaN','Neighbor','Significant others - current or former']

In [9]:
# maakt nieuwe columns met de maand en het jaar

df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year

# zet de index op month
iets = df.set_index(['month'])
iets

# zet index op jaar en dan maand
lekker = df.set_index(['year','month'])
lekker
# # df_date = df.loc[df['incident_characteristics'].str.contains('Officer', 'officer')==True].groupby('month')['n_killed','n_injured']
# # df_date.describe()

# ok = df


# groupies = df.groupby(['year','month'])['n_injured','n_killed']
# groupies.describe()

                                                      address  \
year month
2013 1              1506 Versailles Avenue and Coursin Street
     1                           13500 block of Cerise Avenue
     1                                  1776 East 28th Street
     1                       16000 block of East Ithaca Place
     1                              307 Mourning Dove Terrace
     1                             6000 block of South Owasso
     1                                         2806 Long Lane
     1      LaSalle Street and Martin Luther King Jr. Boul...
     1                             1100 block of Breton Drive
     1                           1500 block of W. Fayette St.
     1                                         1501 Dodds Ave
     1                    W Florissant Ave and Riverview Blvd
     1                           1000 block of Flat Town Road
     1                            2403 Benning Road Northeast
     1                                   601 West Main Street
     2                                      2514 Mount Moriah
     2                            5800 block of Poplar Avenue
     2                         2500 block of East 75th Street
     2                            400 block of Bourbon Street
     2                           800 block of Humboldt Street
     2                                  500 North King Street
     2                  8286 Adams Street and 450 West Street
     2                                         Katella Avenue
     2                   1200 block of North 89th East Avenue
     2                                1447 Grandville Ave. SW
     2                          43145 Business Center Parkway
     2                  2800 block of Mercer University Drive
     3                     7000 block of Burlingame Boulevard
     3                            224 Second Street Northwest
     3                                         4030 Dixie Hwy
...                                                       ...
2018 3                              400 block of Hamilton Ave
     3                                                Ohio St
     3                            600 block of Alabama Ave SE
     3                        Bonanza Rd and Valley View Blvd
     3                               37900 block of 47th St E
     3                                   2300 block of 8th St
     3                         1200 block of Whispering Trail
     3                                      1400 E Peckham Ln
     3                                            Wedekind Rd
     3                                        8660 Miramar Rd
     3                                100 block of Warren Ave
     3                              300 block of Atlantic Ave
     3                                 1700 block of 23rd Ave
     3                  South Kirkman Road and Raleigh Street
     3                                1700 block of Harbor St
     3                                                  US 74
     3                                 1000 block of York Ave
     3                                 500 block of Walnut St
     3                    4200 block of Hillsboro Hematite Rd
     3                                           1100 Park Dr
     3                            3100 block of California St
     3                                  2900 block of Wingate
     3                                                   I-96
     3                                               Hayes Rd
     3                                1 block of N Paulina St
     3                       12600 block of N Willow Crest Ln
     3                     North Riceland Road and Highway 90
     3                                         247 Keyser Ave
     3                              1300 block of Cook Street
     3                                 12630 Ashford Point Dr

                      city_or_county  congressional_district       date  \
year month
2013 1                    Mckeesport                    14.0 2013-01-01
     1                     Hawthorne                    43.0 2013-01-01
     1                        Lorain                     9.0 2013-01-01
     1                        Aurora                     6.0 2013-01-05
     1                    Greensboro                     6.0 2013-01-07
     1                         Tulsa                     1.0 2013-01-07
     1                   Albuquerque                     1.0 2013-01-19
     1                   New Orleans                     2.0 2013-01-21
     1                     Brentwood                     9.0 2013-01-21
     1                     Baltimore                     7.0 2013-01-23
     1                   Chattanooga                     3.0 2013-01-23
     1                   Saint Louis                     1.0 2013-01-25
     1                     Charenton                     3.0 2013-01-26
     1                    Washington                     1.0 2013-01-26
     1                   Springfield                     8.0 2013-01-26
     2                       Memphis                     9.0 2013-02-02
     2                 Yuba (county)                     3.0 2013-02-03
     2                       Chicago                     2.0 2013-02-07
     2                   New Orleans                     2.0 2013-02-09
     2                       Vallejo                     5.0 2013-02-11
     2                    Wilmington                     1.0 2013-02-11
     2                       Midvale                     4.0 2013-02-12
     2               Orange (county)                    46.0 2013-02-19
     2                         Tulsa                     1.0 2013-02-21
     2                  Grand Rapids                     3.0 2013-02-22
     2                     Lancaster                    25.0 2013-02-23
     2                         Macon                     2.0 2013-02-24
     3                    Shreveport                     4.0 2013-03-02
     3                      Moultrie                     8.0 2013-03-03
     3              Saginaw (county)                     5.0 2013-03-03
...                              ...                     ...        ...
2018 3                      Duquesne                    14.0 2018-03-31
     3                        Bangor                     NaN 2018-03-31
     3                    Washington                     NaN 2018-03-31
     3                     Las Vegas                     NaN 2018-03-31
     3                      Palmdale                    25.0 2018-03-31
     3                 Wichita Falls                    13.0 2018-03-31
     3                        Dallas                    30.0 2018-03-31
     3                          Reno                     2.0 2018-03-31
     3                          Reno                     2.0 2018-03-31
     3                     San Diego                    52.0 2018-03-31
     3                     Rochester                    25.0 2018-03-31
     3                       Shafter                    21.0 2018-03-31
     3                       Oakland                     NaN 2018-03-31
     3                       Orlando                    10.0 2018-03-31
     3                      Stockton                     9.0 2018-03-31
     3                Kings Mountain                     NaN 2018-03-31
     3                    Saint Paul                     NaN 2018-03-31
     3                       Guthrie                     3.0 2018-03-31
     3                        Festus                     8.0 2018-03-31
     3                   Saint Clair                     NaN 2018-03-31
     3                   Saint Louis                     NaN 2018-03-31
     3                       Memphis                     9.0 2018-03-31
     3                       Detroit                     NaN 2018-03-31
     3                       Madison                     NaN 2018-03-31
     3                       Chicago                     NaN 2018-03-31
     3      Spokane (Spokane Valley)                     5.0 2018-03-31
     3                         Rayne                     NaN 2018-03-31
     3                  Natchitoches                     4.0 2018-03-31
     3                        Gretna                     2.0 2018-03-31
     3                       Houston                     9.0 2018-03-31

                                  gun_stolen  \
year month
2013 1                                   NaN
     1                                   NaN
     1      {'0': 'Unknown', '1': 'Unknown'}
     1                                   NaN
     1      {'0': 'Unknown', '1': 'Unknown'}
     1                                   NaN
     1      {'0': 'Unknown', '1': 'Unknown'}
     1                                   NaN
     1                                   NaN
     1                                   NaN
     1                      {'0': 'Unknown'}
     1                      {'0': 'Unknown'}
     1                      {'0': 'Unknown'}
     1                      {'0': 'Unknown'}
     1                                   NaN
     2                      {'0': 'Unknown'}
     2                      {'0': 'Unknown'}
     2                                   NaN
     2                      {'0': 'Unknown'}
     2                                   NaN
     2                      {'0': 'Unknown'}
     2                                   NaN
     2                      {'0': 'Unknown'}
     2                                   NaN
     2                                   NaN
     2                                   NaN
     2                                   NaN
     3                                   NaN
     3                      {'0': 'Unknown'}
     3                                   NaN
...                                      ...
2018 3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}
     3                      {'0': 'Unknown'}

                                          gun_type  \
year month
2013 1                                         NaN
     1                                         NaN
     1            {'0': 'Unknown', '1': 'Unknown'}
     1                                         NaN
     1            {'0': 'Handgun', '1': 'Handgun'}
     1                                         NaN
     1      {'0': '22 LR', '1': '223 Rem [AR-15]'}
     1                                         NaN
     1                                         NaN
     1                                         NaN
     1                            {'0': 'Unknown'}
     1                            {'0': 'Unknown'}
     1                            {'0': 'Shotgun'}
     1                            {'0': 'Handgun'}
     1                                         NaN
     2                            {'0': 'Handgun'}
     2                                {'0': '9mm'}
     2                                         NaN
     2                            {'0': 'Handgun'}
     2                                         NaN
     2                            {'0': '45 Auto'}
     2                                         NaN
     2                           {'0': '12 gauge'}
     2                                         NaN
     2                                         NaN
     2                                         NaN
     2                                         NaN
     3                                         NaN
     3                       {'0': '7.62 [AK-47]'}
     3                                         NaN
...                                            ...
2018 3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Handgun'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': '45 Auto'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}
     3                            {'0': 'Unknown'}

                                     incident_characteristics  incident_id  \
year month
2013 1      Shot - Wounded/Injured||Mass Shooting (4+ vict...       461105
     1      Shot - Wounded/Injured||Shot - Dead (murder, a...       460726
     1      Shot - Wounded/Injured||Shot - Dead (murder, a...       478855
     1      Shot - Dead (murder, accidental, suicide)||Off...       478925
     1      Shot - Wounded/Injured||Shot - Dead (murder, a...       478959
     1      Shot - Dead (murder, accidental, suicide)||Hom...       478948
     1      Shot - Dead (murder, accidental, suicide)||Mas...       479363
     1      Shot - Wounded/Injured||Drive-by (car to stree...       479374
     1      Shot - Wounded/Injured||Drive-by (car to stree...       479389
     1      Shot - Wounded/Injured||Shot - Dead (murder, a...       492151
     1      Shot - Wounded/Injured||Shot - Dead (murder, a...       491674
     1      Shot - Wounded/Injured||Shot - Dead (murder, a...       479413
     1      Shot - Wounded/Injured||Shot - Dead (murder, a...       479561
     1      Shot - Wounded/Injured||Mass Shooting (4+ vict...       479554
     1      Shot - Wounded/Injured||Shot - Dead (murder, a...       479460
     2      Shot - Wounded/Injured||Mass Shooting (4+ vict...       479573
     2      Shot - Wounded/Injured||Shot - Dead (murder, a...       479580
     2      Shot - Wounded/Injured||Drive-by (car to stree...       479592
     2      Shot - Wounded/Injured||Mass Shooting (4+ vict...       479603
     2      Shot - Wounded/Injured||Shot - Dead (murder, a...       480311
     2      Shot - Wounded/Injured||Shot - Dead (murder, a...       480327
     2      Shot - Wounded/Injured||Shot - Dead (murder, a...       480344
     2      Shot - Wounded/Injured||Shot - Dead (murder, a...       480358
     2      Shot - Wounded/Injured||Shot - Dead (murder, a...       480383
     2      Shot - Wounded/Injured||Mass Shooting (4+ vict...       480401
     2      Shot - Wounded/Injured||Mass Shooting (4+ vict...       480407
     2      Shot - Wounded/Injured||Mass Shooting (4+ vict...       480443
     3      Shot - Wounded/Injured||Shot - Dead (murder, a...       481186
     3      Shot - Wounded/Injured||Shot - Dead (murder, a...       481198
     3      Shot - Wounded/Injured||Mass Shooting (4+ vict...       481208
...                                                       ...          ...
2018 3      Shot - Dead (murder, accidental, suicide)||Sui...      1082455
     3           Shots Fired - No Injuries||Domestic Violence      1081936
     3                              Shots Fired - No Injuries      1081946
     3      Shots Fired - No Injuries||Home Invasion||Home...      1081949
     3              Shot - Dead (murder, accidental, suicide)      1082266
     3      Shot - Wounded/Injured||Defensive Use||Defensi...      1082483
     3      Shot - Wounded/Injured||Home Invasion||Home In...      1082486
     3      Shot - Dead (murder, accidental, suicide)||Ins...      1083121
     3      Shot - Dead (murder, accidental, suicide)||Sui...      1081947
     3      Institution/Group/Business||Shots Fired - No I...      1082089
     3      Shot - Dead (murder, accidental, suicide)||Sui...      1081901
     3      Shots Fired - No Injuries||Officer Involved In...      1082394
     3              Shot - Dead (murder, accidental, suicide)      1082392
     3                                 Shot - Wounded/Injured      1082057
     3              Shot - Dead (murder, accidental, suicide)      1082091
     3      Shot - Wounded/Injured||Drive-by (car to stree...      1081719
     3      Shot - Wounded/Injured||Drive-by (car to stree...      1082388
     3      Shot - Dead (murder, accidental, suicide)||Off...      1082197
     3                                 Shot - Wounded/Injured      1082023
     3      Shot - Wounded/Injured||Officer Involved Incid...      1082226
     3      Shot - Dead (murder, accidental, suicide)||Acc...      1081894
     3              Shot - Wounded/Injured||Domestic Violence      1082234
     3      Shot - Wounded/Injured||Drive-by (car to stree...      1081742
     3                              Shots Fired - No Injuries      1082990
     3                                 Shot - Wounded/Injured      1081752
     3      Non-Shooting Incident||Possession (gun(s) foun...      1082061
     3                              Shots Fired - No Injuries      1083142
     3      Shot - Dead (murder, accidental, suicide)||Ins...      1083139
     3                                 Shot - Wounded/Injured      1083151
     3              Shot - Dead (murder, accidental, suicide)      1082514

            latitude          location_description          ...           \
year month                                                  ...
2013 1       40.3467                           NaN          ...
     1       33.9090                           NaN          ...
     1       41.4455                   Cotton Club          ...
     1       39.6518                           NaN          ...
     1       36.1140                           NaN          ...
     1       36.2405              Fairmont Terrace          ...
     1       34.9791                           NaN          ...
     1       29.9435                           NaN          ...
     1       37.9656                           NaN          ...
     1       39.2899                           NaN          ...
     1       35.0221                           NaN          ...
     1       38.7067                           NaN          ...
     1       29.8816                           NaN          ...

In [5]:
# selecteer op man en maak onderscheid suspect en victim
man = df_p.loc[df_p['participant_gender']=='Male']
suspect_man = man.loc[man['participant_type']=='Subject-Suspect']
victim_man = man.loc[man['participant_type']=='Victim']

# maak een dict met de het aantal gevallen per leeftijd voor suspect en victim
leeftijden_man_suspect = suspect_man['participant_age'].value_counts().to_dict()
leeftijden_man_victim = victim_man['participant_age'].value_counts().to_dict()

# selecteer op vrouw en maak onderscheid suspect en victim
woman = df_p.loc[df_p['participant_gender']=='Female']
suspect_woman = woman.loc[woman['participant_type']=='Subject-Suspect']
victim_woman = woman.loc[woman['participant_type']=='Victim']

# maak een dict met de het aantal gevallen per leeftijd voor suspect 
leeftijden_woman_suspect = suspect_woman['participant_age'].value_counts().to_dict()
leeftijden_woman_victim = victim_woman['participant_age'].value_counts().to_dict()



# order de dicts en zet in lijst, nieuwe variabelen voor elke groep
x = []
y = []
for  k, v in sorted(leeftijden_man_victim.items()):
   
    x.append(k)
    y.append(v)

x1 = []
y1 = []
for  k, v in sorted(leeftijden_man_suspect.items()):
   
    x1.append(k)
    y1.append(v)

x2 = []
y2 = []
for  k, v in sorted(leeftijden_woman_victim.items()):
   
    x2.append(k)
    y2.append(v)
    
x3 = []
y3 = []
for  k, v in sorted(leeftijden_woman_suspect.items()):
   
    x3.append(k)
    y3.append(v)

In [159]:
# Maak plots


output_file("Gender_age_division_type.html")

p = figure(x_range = (0,100), y_range=(0,6000), title = 'Age division by gender')

p.line(x, y, line_width=2, line_color = "#47A8E5")
p.circle(x, y, size=2,  fill_color = '#47A8E5', line_color="#47A8E5", line_width=3, legend='Male Victim')

p.line(x1, y1, line_width=2, line_color = '#133A7C')
p.circle(x1, y1, size=2,  fill_color = '#133A7C', line_color="#133A7C", line_width=3, legend='Male Suspect')

p.line(x2, y2, line_width=2, line_color = "#FF0800")
p.circle(x2, y2, size=2,  fill_color = '#FF0800', line_color="#FF0800", line_width=3, legend='Female Victim')

p.line(x3, y3, line_width=2, line_color = "#800000")
p.circle(x3, y3, size=2,  fill_color = '#800000', line_color="#800000", line_width=3, legend='Female Suspect')



p.xaxis.axis_label = "Age"
p.xaxis.axis_label_text_color = "#aa6666"
p.xaxis.axis_label_standoff = 30

p.yaxis.axis_label = "Number of Incidents"
p.yaxis.axis_label_text_color = '#aa6666'

show(p)

In [26]:
#maak een df met de jaren en maand als index
ieks = lekker.groupby(['year','month']).size().reset_index(name='count').to_dict()

#voeg bijbehorende key en values toe aan lijst 
maanden = []
count = []
for i in range(0,63):
    maanden.append(i+1)
    count.append(ieks['count'][i])
    
# maak een lineare regressie lijst
regression = np.polyfit(maanden, count, 1)

print(regression)

# nu de waarden invullen voor de regressie
r_x, r_y = zip(*((i, i*regression[0] + regression[1]) for i in range(63)))

[  79.28485023 1267.26574501]

In [27]:
output_file("Month_incidents_troughout.html")

p = figure(x_range = (1,63), y_range=(0,5800), title = 'Number of incidents per month')

p.line(maanden, count, line_width=2, line_color = "#47A8E5")
p.circle(maanden, count, size=2,  fill_color = '#47A8E5', line_color="#47A8E5", line_width=3)


p.line(r_x, r_y, line_width=2, line_color = "red")


p.xaxis.axis_label = "Month"
p.xaxis.axis_label_text_color = "#aa6666"
p.xaxis.axis_label_standoff = 30

p.yaxis.axis_label = "Number of Incidents"
p.yaxis.axis_label_text_color = '#aa6666'

show(p)

In [153]:
a =[]
b = []

for  k, v in sorted(nieuw.items()):
    a.append(k)
    b.append(v)
b

[23091,
 18841,
 22639,
 18628,
 19930,
 18755,
 21126,
 21040,
 19656,
 19890,
 17974,
 18106]

In [162]:

output_file("Month_incidents.html")

p = figure(x_range = (1,12), y_range=(0,25000), title = 'Number of incidents per month')

p.line(a, b, line_width=2, line_color = "#47A8E5")
p.circle(a, b, size=2,  fill_color = '#47A8E5', line_color="#47A8E5", line_width=3)



p.xaxis.axis_label = "Month of the Year"
p.xaxis.axis_label_text_color = "#aa6666"
p.xaxis.axis_label_standoff = 30

p.yaxis.axis_label = "Number of Incidents"
p.yaxis.axis_label_text_color = '#aa6666'

show(p)

In [167]:
df_test

                   participant_relationship  participant_age  count
0                               Aquaintance              1.0      1
1                               Aquaintance              9.0      1
2                               Aquaintance             11.0      1
3                               Aquaintance             13.0      1
4                               Aquaintance             14.0      9
5                               Aquaintance             15.0     12
6                               Aquaintance             16.0     17
7                               Aquaintance             17.0     27
8                               Aquaintance             18.0     32
9                               Aquaintance             19.0     38
10                              Aquaintance             20.0     26
11                              Aquaintance             21.0     31
12                              Aquaintance             22.0     37
13                              Aquaintance             23.0     28
14                              Aquaintance             24.0     31
15                              Aquaintance             25.0     27
16                              Aquaintance             26.0     38
17                              Aquaintance             27.0     32
18                              Aquaintance             28.0     32
19                              Aquaintance             29.0     25
20                              Aquaintance             30.0     26
21                              Aquaintance             31.0     26
22                              Aquaintance             32.0     19
23                              Aquaintance             33.0     14
24                              Aquaintance             34.0     28
25                              Aquaintance             35.0     20
26                              Aquaintance             36.0     19
27                              Aquaintance             37.0     22
28                              Aquaintance             38.0     19
29                              Aquaintance             39.0     17
..                                      ...              ...    ...
822  Significant others - current or former             63.0     15
823  Significant others - current or former             64.0     13
824  Significant others - current or former             65.0     12
825  Significant others - current or former             66.0     10
826  Significant others - current or former             67.0     10
827  Significant others - current or former             68.0     18
828  Significant others - current or former             69.0      9
829  Significant others - current or former             70.0     10
830  Significant others - current or former             71.0     14
831  Significant others - current or former             72.0     13
832  Significant others - current or former             73.0     14
833  Significant others - current or former             74.0      6
834  Significant others - current or former             75.0      6
835  Significant others - current or former             76.0      5
836  Significant others - current or former             77.0      3
837  Significant others - current or former             78.0      5
838  Significant others - current or former             79.0      5
839  Significant others - current or former             80.0      4
840  Significant others - current or former             81.0      4
841  Significant others - current or former             82.0      2
842  Significant others - current or former             83.0      7
843  Significant others - current or former             84.0      3
844  Significant others - current or former             85.0      3
845  Significant others - current or former             86.0      3
846  Significant others - current or former             87.0      2
847  Significant others - current or former             88.0      3
848  Significant others - current or former             92.0      1
849  Significant others - current or former             93.0      2
850  Significant others - current or former             94.0      1
851  Significant others - current or former             96.0      1

[852 rows x 3 columns]